from django.urls import path, include
from .views import *
from accounts.views import UserRegister

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', UserRegister.as_view(), name="register"),
    path('dashboard/users/', UsersView.as_view(), name="users_dashboard"),
    path('dashboard/posts/', PostsDashBoardView.as_view(), name="posts_dashboard"),
    path('blog/models/', blog_dashboard, name="blog_dashboard"),
    path('bottom/models/', AddBottomView.as_view(), name="add_bottom_dashboard"),
    path('contact/models/', AddContactView.as_view(), name="add_contact_dashboard"),
    path('bottom/delete/', delete_bottom, name="delete_bottom_dashboard"),
    path('about/delete/', delete_about, name="delete_about_dashboard"),
    path('about/models/', AddAboutView.as_view(), name="add_about_dashboard"),
    path('terms/models/', AddTermsView.as_view(), name="add_terms_dashboard"),
    path('title/models/', AddTitlesView.as_view(), name="add_title_dashboard"),
    path('social-models/', AddSocialView.as_view(), name="add_social_dashboard"),
    path('top-cover-models/', AddCoverView.as_view(), name="add_top_cover_dashboard"),
    path('terms/delete/', delete_terms, name="delete_terms_dashboard"),
    path('social/delete/', delete_social, name="delete_social_dashboard"),
    path('title/delete/', delete_titles, name="delete_title_dashboard"),
    path('contact/delete/', delete_contact, name="delete_contact_dashboard"),
    path('top_cover/delete/', delete_cover, name="delete_top_cover_dashboard"),
    path('profile/detail/<int:pk>/<slug:user>/', ProfileDetailView.as_view(), name="profile_detay"),
    path('edit/<pk>/<username>/', UserEditView.as_view(), name="user_edit"),
    path('profile/<pk>/<username>/', ProfileView.as_view(), name="profile"),
    path('user_edit/<int:pk>/<slug:username>/', UserUpdateView.as_view(), name="user_update"),
    path('profile_edit/<pk>/<username>/', ProfileUpdateView.as_view(), name="profile_update"),
    path('delete_user/<int:pk>/', UserDeleteView.as_view(), name="user_delete"),
    path('kullanıcı_sil/<int:pk>/', dash_user_delete, name="dash_user_delete"),
    path('messages/<int:pk>/<slug:name>/', MessageDetail.as_view(), name="messages"),
    path('messages/<int:pk>/', MessageDeleteView.as_view(), name="message_delete"),
    path('password/<pk>/<username>/', PasswordChance.as_view(), name="password_change"),
    path('settings/<pk>/<username>/', settings, name="settings"),
    path('kullanıcı/messages/<int:pk>/<username>/', UserMessagesListView.as_view(), name="user_messages"),
    path('kullanıcı/messages/detay/<slug:sender>/<int:pk>/<slug:title>/', UserMessagesDetailView.as_view(),
         name="user_messages_detail"),
    path('kullanıcı/messages/sil/<int:pk>/', user_messages_delete,
         name="user_messages_delete"),
    path('delete_readed/messages/<username>/', user_mesaasges_delete_all_read, name="user_mesaasges_delete_all_read"),
    path('sent-messages/<int:pk>/<username>/', user_sent_message, name="user_sent_message"),
    path('user_reply_message/<int:pk>/<username>/<int:user_pk>/', user_reply_message, name="user_reply_message"),
]
