# Generated by Django 4.1 on 2022-08-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlastQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blast', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FastaRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=1000)),
                ('sequence', models.TextField()),
            ],
            options={
                'verbose_name': 'Fasta Okuması',
                'verbose_name_plural': 'Fasta Okumaları',
                'db_table': 'fasta_read',
            },
        ),
        migrations.CreateModel(
            name='GenbankRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=255)),
                ('sequence', models.TextField()),
                ('description', models.CharField(max_length=1000)),
                ('features', models.TextField()),
                ('dbxrefs', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Genbank Okuması',
                'verbose_name_plural': 'Genbank Okumaları',
                'db_table': 'genbank_read',
            },
        ),
        migrations.CreateModel(
            name='MedlineArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('article_id', models.CharField(max_length=1000)),
                ('doi', models.CharField(default='', max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('term', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='PubMedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('article_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=1000)),
                ('link', models.URLField(default='https://pubmed.ncbi.nlm.nih.gov/')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'PubMed Makale',
                'verbose_name_plural': 'PubMed Makale',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='labratory/')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slide',
                'db_table': 'slide',
            },
        ),
    ]
