# Generated by Django 4.0.6 on 2022-07-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Fasta', max_length=100)),
                ('gene', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fasta',
            },
        ),
    ]
