# Generated by Django 4.1.2 on 2022-10-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictionmodel',
            name='enzymes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Enzim Adı'),
        ),
        migrations.AlterField(
            model_name='restrictionmodel',
            name='site',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Bölge Adı'),
        ),
        migrations.AlterField(
            model_name='restrictionusermodel',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
