# Generated by Django 4.1 on 2022-09-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genbankread',
            name='protein_sequence_len',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Protein Uzunluğu'),
        ),
    ]
