# Generated by Django 4.1.1 on 2022-09-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplesequencealignment',
            name='algoritma',
            field=models.CharField(choices=[('', '------------'), ('nj', 'Neighbor Joining'), ('upgma', 'UPGMA')], max_length=1000, verbose_name='Filogenetik Ağaç Türü'),
        ),
        migrations.AlterField(
            model_name='multiplesequencealignment',
            name='alignment_filetype',
            field=models.CharField(choices=[('', '------------'), ('fasta', 'FASTA'), ('clustal', 'CLUSTAL'), ('nexus', 'NEXUS')], max_length=1000, verbose_name='Alignment Dosya Tipi'),
        ),
    ]
