# Generated by Django 3.2.16 on 2022-11-19 09:29

import bioinformatic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplesequencealignment',
            name='cluster_csv',
            field=models.FileField(blank=True, null=True, upload_to=bioinformatic.models.upload_to, verbose_name='ClusterGram CSV Dosyası'),
        ),
    ]
