# Generated by Django 4.1.2 on 2022-10-06 07:53

import bioinformatic.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bioinformatic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastaDNAMotifModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif_file', models.FileField(upload_to=bioinformatic.models.upload_to_motif, verbose_name='Motif Nucleotit Sekans Dosyası')),
                ('matrix_position_file', models.FileField(blank=True, null=True, upload_to=bioinformatic.models.upload_to_motif, verbose_name='BlastXML Dosyası')),
                ('position_weight_matrices', models.FileField(blank=True, null=True, upload_to=bioinformatic.models.upload_to_motif, verbose_name='HSP Dosyası')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Laborant')),
            ],
            options={
                'verbose_name': 'Fasta DNA Sekans Motif',
                'verbose_name_plural': 'Fasta DNA Sekans Motif',
            },
        ),
    ]
