# Generated by Django 4.1.1 on 2022-09-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0002_alter_multiplesequencealignment_algoritma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplesequencealignment',
            name='method',
            field=models.CharField(choices=[('', '------------'), ('MUSCLE', 'MUSCLE'), ('clustalw2', 'CLUSTALW2'), ('omega', 'ClustalOmega')], max_length=1000, verbose_name='Multiple Sekans Alignment Aracı'),
        ),
    ]
