# Generated by Django 4.1.3 on 2022-11-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0002_multiplesequencealignment_cluster_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphicmodels',
            name='format',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Dosya Formatı'),
        ),
    ]
