# Generated by Django 4.1.2 on 2022-10-06 20:45

import bioinformatic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0002_fastadnamotifmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastadnamotifmodel',
            name='position_score_matrices',
            field=models.FileField(blank=True, null=True, upload_to=bioinformatic.models.upload_to_motif, verbose_name='HSP Dosyası'),
        ),
    ]
