# Generated by Django 4.0.6 on 2022-07-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0002_fasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasta',
            name='sekans',
            field=models.TextField(default=''),
        ),
    ]
