# Generated by Django 4.0.6 on 2022-07-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0003_fasta_sekans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Genbank', max_length=100)),
                ('gene', models.CharField(max_length=255)),
                ('sekans', models.TextField()),
                ('description', models.CharField(max_length=1000)),
                ('dbxrefs', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Genbank',
                'verbose_name_plural': 'Genbank',
                'db_table': 'genbank',
            },
        ),
        migrations.AlterModelOptions(
            name='fasta',
            options={'verbose_name': 'Fasta', 'verbose_name_plural': 'Fasta'},
        ),
    ]
