# Generated by Django 4.1.2 on 2022-10-06 20:50

import bioinformatic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0003_fastadnamotifmodel_position_score_matrices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fastadnamotifmodel',
            name='matrix_position_file',
        ),
        migrations.RemoveField(
            model_name='fastadnamotifmodel',
            name='position_score_matrices',
        ),
        migrations.RemoveField(
            model_name='fastadnamotifmodel',
            name='position_weight_matrices',
        ),
        migrations.AddField(
            model_name='fastadnamotifmodel',
            name='mpf',
            field=models.FileField(blank=True, null=True, upload_to=bioinformatic.models.upload_to_motif, verbose_name='Nucleotide matrix position'),
        ),
        migrations.AddField(
            model_name='fastadnamotifmodel',
            name='pssm',
            field=models.FileField(blank=True, null=True, upload_to=bioinformatic.models.upload_to_motif, verbose_name='Compute position weight matrices.'),
        ),
        migrations.AddField(
            model_name='fastadnamotifmodel',
            name='pwm',
            field=models.FileField(blank=True, null=True, upload_to=bioinformatic.models.upload_to_motif, verbose_name='Compute position specific scoring matrices'),
        ),
    ]
