# Generated by Django 4.1.1 on 2022-09-10 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0003_multiplesequencealignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleSequenceAlignment',
        ),
    ]
