# Generated by Django 4.0.6 on 2022-07-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0004_genbank_alter_fasta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='genbank',
            name='features',
            field=models.TextField(default=''),
        ),
    ]
