# Generated by Django 4.1.3 on 2022-11-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0004_alter_multiplesequencealignment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecularmodel',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tip'),
        ),
    ]
