# Generated by Django 4.1.3 on 2022-11-29 16:06

import bioinformatic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0006_rename_type_molecularmodel_id_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecularmodel',
            name='file_path',
            field=models.FilePathField(blank=True, null=True, path=bioinformatic.models.molecule_path),
        ),
        migrations.AlterField(
            model_name='molecularmodel',
            name='id_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id'),
        ),
    ]
