# Generated by Django 4.2.3 on 2023-08-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0009_molecularmodel_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labslidemodel',
            name='content',
            field=models.TextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='labslidemodel',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Alt Başlık:'),
        ),
        migrations.AlterField(
            model_name='labslidemodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
    ]
