from django.urls import path
from bioinformatic import views
from django.views.generic import RedirectView

app_name = "bioinformatic"

urlpatterns = [
    path('bioinformatik-labratory-home/', views.BioinformaticHomeView.as_view(), name="home"),
    path('dna-sequence/', views.sekans, name="sekans_analiz"),
    path('translasyon/', views.translation, name="translation"),
    path('download-fasta/', views.fasta_download, name="fasta_download"),
    path('combine-fasta-download/', views.combine_fasta_download, name="combine_fasta_download"),
    path('fasta-writing/', views.fasta_writing, name="fasta_writing"),
    path('fasta-motif/', views.fasta_motif, name="fasta_motif"),
    path('fasta-add/', views.fasta_add, name="fasta_add"),
    path('fasta-combine/', views.fasta_file_combine, name="fasta_file_combine"),
    path('genbank-read/', views.genbank_read, name="genbank_read"),
    path('fasta-file-translate/', views.fasta_file_translate, name="fasta_file_translate"),
    path('fasta-protein-download/', views.fasta_protein_download, name="fasta_protein_download"),
    path('genbank-region/', views.GenBankResultView.as_view(), name="genbank_region"),
    path('genome-diagram/', views.genome_diagram, name="genome_diagram"),
    path('add-enzyme/<pk>/', views.add_enzyme, name="add_enzyme"),
    path('update-enzyme/<pk>/', views.update_enzyme, name="update_enzyme"),
    path('delete-enzyme/<pk>/', views.delete_enzyme, name="delete_enzyme"),
    path('plot/<pk>/<user>/<graph_type>/', views.plot, name="plot"),
    path('plot-secimi/', views.plot_select, name="plot_select"),
    path('genome-diagram-download/', views.genome_diagram_pdf_download, name="genome_diagram_pdf_download"),
    path('histogram_download/', views.histogram_download, name="histogram_download"),
    path('gc-plot-download/', views.gc_plot_download, name="gc_plot_download"),
    path('dot-plot-download/', views.dot_plot_download, name="dot_plot_download"),
    path('file-convert/', views.file_convert, name="file_convert"),
    path('plot/<graph_type>/<user>/<created>/<pk>/', views.PlotDetailView.as_view(), name="plot_results"),
    path('fasta_dot_plot/', views.fasta_dot_plot, name="fasta_dot_plot"),
    path('genome-diagram-download-image/', views.genome_diagram_image_download, name="genome_diagram_image_download"),
    path('genbank-region/<int:pk>/<slug:organism>/', views.GenbankDetailView.as_view(), name="genbank_detail"),
    path('delete-genbank/', views.delete_genbank, name="genbank_delete"),
    path('download-genbank/', views.genbank_download, name="genbank_download"),
    path('genbank-writing/', views.genbank_writing, name="genbank_writing"),
    path('local-alignment/', views.local_alignment, name="local_alignment"),
    path('local-alignment-download/', views.local_alignments_download, name="local_alignment_download"),
    path('global-alignment/', views.global_alignment, name="global_alignment"),
    path('multiple-sequence-alignment/', views.MultipleSequenceAlignmentView, name="multiple_sequence_alignments"),
    path('multiple-sequence-alignment/<user>/<method>/', views.MultipleSeqAlignment,
         name="multiple_sequence_alignments_analiz"),
    path('global-alignment-download/', views.global_alignments_download, name="global_alignment_download"),
    path('fasta-blast-tools/', views.fasta_blast_tools, name="fasta_blast_tools"),
    path('xml-hsp/', views.hsp_download, name="xml_hsp"),
    path('entrez-file-search/', views.entrez, name="entrez_file_search"),
    path('entrez-file-download/', views.entrez_download, name="entrez_file_download"),
    path('pubmed-articles-id/', views.pubmed, name="pubmed_article"),
    path('pubmed-articles-term/', views.medline_article, name="medline_article"),
    path('filogenetik-agac-download/', views.tree_download, name="tree_download"),
    path('swiss-prot/', views.swiss_prot_file, name="swiss_prot_file"),
    path('swiss-prot-url/', views.swiss_prot_url, name="swiss_prot_url"),
    path('swiss_prot-download/', views.swiss_download, name="swiss_prot_download"),
    path('swiss_prot-table/', views.swiss_list_view, name="swiss_prot_list"),
    path('muscle-aligned-download/', views.muscle_aligned_download, name="muscle_aligned_download"),
    path('maxlike_aligned_download/', views.aligned_download, name="aligned_download"),
    path('phylo_tree_download/', views.phylo_tree_download, name="phylo_tree_download"),
    path('maxlike_stats_download/', views.maxlike_stats_download, name="maxlike_stats_download"),
    path('maxlike_scores_download/', views.maxlike_scores_download, name="maxlike_scores_download"),
    path('blast-xml-download/', views.blast_xml_download, name="blast_xml_download"),
    path('blast-hsp-download/', views.blast_hsp_download, name="blast_hsp_download"),
    path('clustal-stats-download/', views.clustal_stats_download, name="clustal_stats_download"),
    path('clustal-scores-download/', views.clustal_scores_download, name="clustal_scores_download"),
    path('motif-download/', views.motif_download, name="motif_download"),
    path('jaspar-motif-download/', views.jaspar_motif_download, name="jaspar_motif_download"),
    path('pssm-download/', views.pssm_download, name="pssm_download"),
    path('pwm-download/', views.pwm_download, name="pwm_download"),
    path('molecule-analiz/', views.molecule3dviewer, name="molecule_analiz"),
    path('multiplemoleculeviewer/', views.multiplemoleculeviewer, name="multiplemoleculeviewer"),
    path('molecule-viewer/<slug:user>/<int:pk>/<id_name>/<created>/', views.Molecule3DView.as_view(), name="molecule3dviewer"),
    path('multiplemoleculeviewer/<slug:user>/<int:pk>/<created>/', views.MultipleMoleculeView.as_view(), name="ngl_molecule_detail"),
    path('molecule-detail/<slug:user>/<int:pk>/<created>/', views.MoleculeDetailView.as_view(), name="molecule_detail"),
    path('jaspar-motif-create/', views.jaspar_motif_create, name="jaspar_motif_create"),
    path('nucleotid-matrix-positions-download/', views.nucleotid_matrix_positions_download,
         name="nucleotid_matrix_positions_download"),
    path('clustal-alignment-download/', views.clustal_alignment_download, name="clustal_alignment_download"),
    path('maximum-likelihood/<user>/<method>/', views.maxlikehood, name="maximum_likelihood"),
    path('maximum-likelihood-download/', views.maximum_likelihood_download, name="maximum_likelihood_download"),
    path('PhyloXML-download/', views.PhyloXML_download, name="PhyloXML_download"),
    path('clustal-omega-alignment/', views.clustalomega_alignment_download, name="clustalomega_alignment_download"),
    path('swiss_prot/<int:pk>/<slug:accessions>/', views.SwissProtDetailView.as_view(), name="swiss_prot_detail"),
    path('add-file-format/', views.add_file_format, name="add_file_format"),
    path('file-formats/', views.file_formats, name="edit_file_format"),
    path('<pk>/delete-file-format/', views.file_format_delete, name="file_format_delete"),
    path('MultipleSeqAignmentResults/<user>/<method>/<slug:molecule_type>/<pk>/', views.MultipleSeqDetailView.as_view(),
         name="msa_results"),
    path('alignment-chart/<user>/<method>/<molecule_type>/<pk>/', views.AlignmentChartView.as_view(),
         name="alignment_chart_show"),
    path('phylogenetic_tree/<slug:tree_type>/<slug:user>/<slug:method>/<molecule_type>/<pk>/',
         views.PhyloTreeDetailView.as_view(), name="phylogenetic_tree"),
    path('clustergram/<slug:tree_type>/<slug:user>/<slug:method>/<molecule_type>/<pk>/',
         views.AlignmentClusterGramView.as_view(), name="clustergram_showing"),
    path('maximumlikelihood-download/', views.maxlike_download, name="max_download"),
]
