# Generated by Django 4.1.5 on 2023-08-16 20:30

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Konu:')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('Okundu', 'Okundu'), ('Okunmadı', 'Okunmadı')], default='Okunmadı', max_length=50, verbose_name='Görülme Durumu')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_receiver', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı: ')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sender', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen: ')),
            ],
            options={
                'verbose_name': 'Kullanıcı Mesajları',
                'verbose_name_plural': 'Kullanıcı Mesajları',
                'db_table': 'messages',
                'ordering': ['-created'],
            },
        ),
    ]
