# Generated by Django 4.1.5 on 2023-08-14 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usermessagesmodel_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessagesmodel',
            name='receiver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messages_receiver', to='accounts.profile', verbose_name='Alıcı: '),
        ),
        migrations.AlterField(
            model_name='usermessagesmodel',
            name='sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sender', to='accounts.profile', verbose_name='Gönderen: '),
        ),
    ]
