# Generated by Django 4.1.5 on 2023-08-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usermessagesmodel_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessagesmodel',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Konu:'),
        ),
    ]
