# Generated by Django 4.1.5 on 2023-08-17 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad-Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('Okundu', 'Okundu'), ('Okunmadı', 'Okunmadı')], default='Okunmadı', max_length=50, verbose_name='Görülme Durumu')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_messages_receiver', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı: ')),
            ],
            options={
                'verbose_name': 'Yazar Mesajları',
                'verbose_name_plural': 'Yazar Mesajları',
                'db_table': 'author_messages',
                'ordering': ['-created'],
            },
        ),
    ]
