# Generated by Django 4.1.5 on 2023-08-17 12:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_authormessages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorMessages',
            new_name='AuthorMessagesModel',
        ),
    ]
